# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MTc0MGQyYjI3OTFiMDBjNDNjYTI4MDFmMWQ0MDBkM2Y5ZDA2NzllMDdiMTE1OGIxZTM0ZThkY2I5YjlhMTYxOGZkY2E5NzEyMDVlMWEzMjJlMmJmZTExYjcxZWRjNTEwZmFkY2RjNDU5NGU1ZWI1YjJhOWFlOTNhY2Q2MTcyODE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
